targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|op_builder:
        enabled: true
        options:
          schema: li|lib/github/schema.public.graphql
      gql_build|data_builder:
        enabled: true
        options:
          schema: li|lib/github/schema.public.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: li|lib/github/schema.public.graphql
