name: li
description:
  Tools used by Yuqian Li

author: Yuqian Li <liyuqian@google.com>
homepage: https://github.com/liyuqian/li
version: 0.1.5

executables:
  li: li

dependencies:
  args: ^1.5.2
  collection: ^1.14.12
  graphql : ^3.0.0
  gql_exec: ^0.2.0
  meta: any
  path: any

dev_dependencies:
  test: ^1.6.8
  pedantic: ^1.8.0
  gql_build: any
  build_runner: any

environment:
  sdk: ">=2.2.2 <3.0.0"